# Generated by Django 5.1.4 on 2024-12-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_stock_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="field_of_work",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="ipo_percentage",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="last_52_weeks_high",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="last_5_years_gain",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="pe_ratio",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="price_today",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="volume",
        ),
        migrations.AddField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
