# Generated by Django 5.1.4 on 2024-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_stock_field_of_work_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="stock",
            name="field_of_work",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="ipo_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="last_52_weeks_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="last_5_years_gain",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="pe_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="price_today",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="volume",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
