# Generated by Django 5.1.4 on 2024-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_stock_last_updated_stock_field_of_work_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
